### ISSUE TITLE
parmas 'search' is not correct??

### ISSUE THREAD

**Issue by bigrain220** [cdnjs/api-server#71] opened 2022-04-29 10:29 UTC
![image](https://user-images.githubusercontent.com/42227852/165927609-4daeba27-6596-4342-8347-c3e11054fc22.png)

i want to get the same data as the picture show from you website,
so i send address:''https://api.cdnjs.com/libraries?search=jquery&limit=5".
But it doesnot work. The data returned is not correct.
what should i do? help me please!

**Comment by MattIPv4** [comment] 2022-04-29 11:23
👋 You can take a look at the code doing the API search here, it is just making a call to Algolia: https://github.com/cdnjs/api-server/blob/master/routes/libraries.js

Similarly, you can compare the code doing the search in the website here, it is also just making a call to Algolia: https://github.com/cdnjs/static-website/blob/master/components/search/inline_search.vue

The key difference is that the API uses `browseObjects` to allow fetching of every result programmatically from Algolia, whereas the client uses a pure search which is much more restricted in terms of the number of results that are returned. I suspect that doing a pure search introduces other ranking factors that `browserObjects` does not consider.

**Comment by MattIPv4** [comment] 2022-07-29 01:06
Closing as intended behaviour.

**Closed by MattIPv4** 2022-07-29 01:06 UTC
